### ISSUE TITLE
Dynamo

### ISSUE THREAD

**Issue by iwarner** [ngneat/nx-serverless#11]
Issue with Table generation

POST /dev/auth/sign-up (λ: sign-up)
One of the tables was not found, verify table exists before retrying. Error: Cannot do operations on a non-existent table

Run the create user curl and get the above

NB// Also add docs about setting up AWS credentials and the defaults needed perhaps

**Comment by NetanelBasal** [comment]
Did you run `npm run localstack`?

**Comment by jhonpedro** [comment]
I did it over here and this error continues to happen.

What should happen when we run our docker-compose? It should create the tables?

**Comment by NetanelBasal** [comment]
It starts dynamodb, then you need to run `npm run serve`

**Comment by jhonpedro** [comment]
Strange that it doesn't work 

But if the sls offline starts it, creates the Dynamo tables in the Localstack instance too?

**Comment by NetanelBasal** [comment]
Yes

**Comment by ghost** [comment]
I had the same issue. After running `npm run localstack` and `npm run serve` the `dev-AppTable` was not created. I'm not sure the process in which this would be created in the `localstack` env but the `core` service does not include a `sls offline` command.

The workaround for me was to use the `NoSQL Workbench` as described in the `README.MD`. Once you connect to your localstack dynamoDB, you can simply create the table.

I would, however, like to know how to automate this process so local development is not so manual if you need to add another table/queue/etc...

**Comment by NetanelBasal** [comment]
Interesting. I'll take a look.

**Comment by NetanelBasal** [comment]
`npx nx deploy core --stage local`

**Comment by NetanelBasal** [comment]
I added it to the docs.

**Comment by ghost** [comment]
Thanks! Does `npx nx deploy core --stage local` not deploy things to your cloud env?

I currently do not have a `local` aws profile. Is that something that needs to be setup?

**Comment by NetanelBasal** [comment]
No, this is how you deploy it to localstack. Yes, you need to create it and put dummy values.

**Comment by ghost** [comment]
Ah okay, makes sense. Ty for this.
